# Include this file from the nginx http block.
map $uri $docs_language {
    ~^/en(?:/|$)  en;
    ~^/zh(?:/|$)  zh-CN;
    default       ru;
}

map $uri $docs_unprefixed_path {
    ~^/(?:en|zh)(?<docs_path>/.*)$  $docs_path;
    ~^/(?:en|zh)$                   /;
    default                         $uri;
}
